# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWSH-KmpzfjgUOFSg0ZSQyXiKxiDPGn-
"""

#dc motor speed control pid simulation
motor_params={
    "R":1.0,
    "L":0.5,
    "K":0.01,
    "J":0.01,
    "B":0.1
}
print("motor_parameters:",motor_params)
import matplotlib.pyplot as plt
speed=[100,500,300,400,250]
time=[0.1,0.2,0.3,0.4,0.5]
plt.plot(time,speed,marker='h')
plt.xlabel('time(sec)')
plt.ylabel('speed(rpm)')
plt.title('time vs speed')
plt.show()